# Generated by Django 5.1.4 on 2026-06-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.BigIntegerField(unique=True)),
                ('credit_score', models.IntegerField(default=100)),
                ('trade_count', models.IntegerField(default=0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seller_credit',
            },
        ),
        migrations.CreateModel(
            name='UserPointAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('total_earned', models.IntegerField(default=0)),
                ('total_spent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_point_account',
            },
        ),
    ]
